@startuml

left to right direction
actor "User" as Us

rectangle Logiciel {

    usecase "écrire" as ec
    usecase "afficher" as af
    usecase "sélectionner zone de texte" as select
    usecase "copier" as copy
    usecase "couper" as cut
    usecase "coller" as paste
}

Us -- ec
af ..> ec : <<include>>
Us -- select
select <.. copy  : <<extends>>
select <.. cut   : <<extends>>
select <.. paste : <<extends>>

@enduml

/' USECASE ECRIRE
    But : 
    Début : 
    Fin : 
    Acteurs : 
    Enchainements :
        1 - 
        2 - 
    Alternatives : 
        1 - 
    Excpetions : 
        1 - 
'/


/'  USECASE COLLER
    But : coller un texte a la place de la selection
    Début : l'utilisateur veut coller une zone de texte
    Fin : l'utilisateur a coller le texte
    Acteurs : Utilisateur
    Enchainements :
        1 - l'utilisateur ouvre le menu
        2 - l'utilisateur selectionne une zone
        3 - l'utilisateur colle le texte
    Alternatives : 
        1 - le logiciel remplace le texte dans la zone de selection si cette derniere n'est pas vide a l'etape 3
    Excpetions : 
        1 - 
'/