@startuml

left to right direction
actor "User" as Us

rectangle Logiciel {

    usecase "écrire" as ec
    usecase "afficher" as af
    usecase "sélectionner zone de texte" as select
    usecase "copier" as copy
    usecase "couper" as cut
    usecase "coller" as paste
}

Us -- ec
af ..> ec : <<include>>
Us -- select
select <.. copy  : <<extends>>
select <.. cut   : <<extends>>
select <.. paste : <<extends>>

@enduml

/' USECASE ECRIRE
    But : 
    Début : 
    Fin : 
    Acteurs : 
    Enchainements :
        1 - 
        2 - 
    Alternatives : 
        1 - 
    Excpetions : 
        1 - 
'/