@startuml

left to right direction
actor "User" as Us

rectangle Logiciel {

    usecase "écrire" as ec
    usecase "afficher" as af
    usecase "sélectionner zone de texte" as select
    usecase "copier" as copy
    usecase "couper" as cut
    usecase "coller" as paste
}

Us -- ec
af ..> ec : <<include>>
Us -- select
select <.. copy  : <<extends>>
select <.. cut   : <<extends>>
select <.. paste : <<extends>>

@enduml

/' USECASE COPIER
    But : Copier la selection
    Début : L'utilisateur veut copié une zone du texte
    Fin : L'utilisateur a copié
    Acteurs : Utilisateur
    Enchainements :
        1 - L'utilisateur selectionne la zone de texte qu'il veut copier
        2 - L'utilisateur copie ensuite la zone de texte à l'aide d'une commande
'/

/' USECASE COUPER
    But : Couper la selection
    Début : L'utilisateur veut coupé une zone du texte
    Fin : L'utilisateur a coupé
    Acteurs : Utilisateur
    Enchainements :
        1 - L'utilisateur selectionne la zone de texte qu'il veut couper
        2 - L'utilisateur copie ensuite la zone de texte
        3 - Le logiciel supprime le texte dans la zone selectionné
'/

/' USECASE SELECTION DE TEXTE
    But : Selectionner du texte
    Début : L'utilisateur veut selectionner une zone du texte
    Fin : L'utilisateur a selectionné une zone de texte
    Acteurs : Utilisateur
    Enchainements :
        1 - L'utilisateur place le curseur de début au bon endroit
        2 - L'utilisateur place le curseur de fin au bon endroit
'/