@startuml classDiagram
skinparam groupInheritance 4
skinparam Linetype polyline


class Application {
 
}

class Window {

}

class ZoneDeTravail {
    ZoneDeTravail Instance

    String Texte
    String Buffer
    Int posCursor1
    Int posCursor2

    moveCursor(int nbCursor, int offset)
    copy()
    paste()
    delete()
    Insertchar(char a)
}

class Input {
    keyPressed()
}

class Script{
    getListEvent()
}

abstract Command {
    Execute()
}

abstract MoveCursor {
    int cursor
    int offset
    Execute()
}

class MoveCursor1 {
    Execute()
}
class MoveCursor2 {
    Execute()
}

class Copy {
    Execute()
}

class Delete{
    Execute()
}

class Paste {
    Execute()
}

class Cut {
    Execute()
}

class InsertChar {
    char caracter
    Execute()
    getKey()
}

class ToggleScript{
    Execute()
}

class UseScript{
    Execute()
}

Application "1" *-- "1" ZoneDeTravail
Application *-- Input
Application *-- Window
Input *-- Command
ZoneDeTravail -- Command

Command <|--- MoveCursor
Command <|--- Delete
Command <|--- Copy

Command <|--- Paste
Command <|--- Cut
Command <|--- InsertChar

Command <|--- ToggleScript
Command <|--- UseScript

MoveCursor <|-- MoveCursor1
MoveCursor <|-- MoveCursor2

Command --* Cut : Copy, Delete
Command --* InsertChar : Delete
Command --* Paste : Delete
Input -- InsertChar : getKey
Window -- ZoneDeTravail

Input "*" -- "1" Script : listEvent
Input -- ToggleScript : toggleScript
Script --* UseScript : listInput
@enduml