@startuml sequence cut
title Diagramme sequence cut
actor User
participant Application
participant Input
participant Cut
participant Copy
participant Delete
participant Zone_de_travail

activate Zone_de_travail
activate User
activate Application
User -> Application : keys

Application -> Input : keys
activate Input
Input -> Cut : KeyPressed()
activate Cut
deactivate Input
Cut -> Copy : Execute()
activate Copy
Copy -> Zone_de_travail : copier le texte
deactivate Copy
Cut -> Delete : Execute()
activate Delete
deactivate Cut


Delete -> Zone_de_travail : supprimer le texte
deactivate Zone_de_travail
@enduml

@startuml InsertChar
title Diagramme sequence InsertChar
actor User as user
participant Application as app
participant Input as input
participant InsertChar as insert
participant ZoneDeTravail as text

user -> app : Appuie sur une touche
activate user
app -> input : Touche appuyée

input -> insert : Invoque la commande
activate insert

insert -> input : Demande le caractère
input -> insert : Renvoie le dernier caractère
insert -> text : Insere le caractère
deactivate insert
deactivate user
@enduml