@startuml

left to right direction
actor "User" as Us

rectangle Logiciel {

    usecase "écrire" as ec
    usecase "afficher" as af
    usecase "sélectionner zone de texte" as select
    usecase "copier" as copy
    usecase "couper" as cut
    usecase "coller" as paste
    
}

Us -- ec
af ..> ec : <<include>>
Us -- select
select <.. copy  : <<extends>>
select <.. cut   : <<extends>>
select <.. paste : <<extends>>

@enduml

/' USECASE ECRIRE
    But : Ajouter du texte dans la zone de travail
    Début : le logiciel attend une entrée
    Fin :  le logiciel ajoute une entrée
    Acteurs : Utilisateur
    Enchainements :
        1 - Le logiciel capte le nouveau caractère
        2 - Le logicièl ajoute le carctère à la zone de travail
        3 - le logiciel repasse en attente
    Alternatives : 
        2 - l'utilisateur saisie un autre caractère, change de mode
    Excpetions : 
'/

/' USECASE AFFICHER
    But : Afficher la zone de travail
    Début : Du texte à été rentrée 
    Fin :  le texte à été affiché
    Acteurs : 
    Enchainements :
        1 - Le logiciel affiche le contenue de la zone de travail
    Alternatives :
    Excpetions : 
'/